{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.irsaRoleArn }}"
  labels:
    {{- include "the-redemption.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
