apiVersion: v1
kind: Service
metadata:
  name: the-redemption
  namespace: {{ .Values.namespace }}
  labels:
    app: the-redemption
    {{- include "the-redemption.labels" . | nindent 4 }}
spec:
  selector:
    app: the-redemption
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  type: ClusterIP
